### ISSUE TITLE
draw point styling

### ISSUE THREAD

**Issue by parkersweb** [camoconnell/lazy-line-painter#17]
Hi - I'd love to use this to show a hand drawing the lines - is it possible to style an element positioned at the drawing point?

**Comment by camilawaz** [comment]
its anyone having troubles with firefox and mac dispositives?

**Comment by camoconnell** [comment]
For future searches on this topic.
Theres been a bunch of changes over the past year, including the removal of Raphaël as dependency.
For this reason the above approach won't work.

Im happy to announce, with the most recent commit, 62937ca, you can now position elements at the drawing point! Using onStrokeUpdate. See /examples/get.html

**Comment by computermacgyver** [comment]
@camoconnell This is awesome. Thank you.
