### ISSUE TITLE
Error: svgData is undefined

### ISSUE THREAD

**Issue by strigga** [camoconnell/lazy-line-painter#34]
Hello,
i get following error in console:

TypeError: c.svgData[d] is undefined
...eKey?c.overrideKey:b.attr("id").replace("#",""),f=c.svgData[d].dimensions.width

and if i embed the minified JS file then i get this error:

TypeError: options.svgData[target] is undefined
var w = options.svgData[target].dimensions.width;

**Comment by camoconnell** [comment]
For future reference.
This will happen if the id of the DOM element your initialising lazylinepainter() on doesn't match the key within your svgData.

For example, the following will work because ``demo`` is being used consistently as an id;

```js
var svgData = {
	'demo' : {
		'paths' : [
			{ 'path': "M144.869,199c0....", 'duration':300 }, 
            { 'path': "M155.85,29c0....",  'duration':1000 }
		]
	}
};

$('#demo').lazylinepainter({
     'svgData': svgData
}); 
```
