### ISSUE TITLE
Dots before draw on Safari and Firefox

### ISSUE THREAD

**Issue by kimwebParis** [camoconnell/lazy-line-painter#36]
Hi,

I have a problem and can't solve it yet. Dots appears before the animation...Does anyone knows how to solve this?
You can see it here: http://www.fevre-gaucher.com/dev/

On Chrome there is no problem, it's only on Firefox and Safari (may be on IE too but I can't check it)

Thanks very much and thanks for your work on this code

**Comment by camilawaz** [comment]
Are you using rafael.js? My project used to have the same problem, and it solved! 
This article was very useful for me: http://blog.teamtreehouse.com/svg-path-animation-with-jquery-and-illustrator

**Comment by camilawaz** [comment]
Also, check the version. I'm using 1.1, because 1.5.1 not work for me :(

**Comment by kimwebParis** [comment]
Hi!

Thanks for your very quick answer!
I'm not on my computer anymore but will test it as soon as possible and let you know

Best regards
Fanny

**Comment by camilawaz** [comment]
I was think in open a issue, but I made a hard search and found this solution. 
When I come back, your issue was open. hehe
I hope it helps you! 

Good luck!

**Comment by kimwebParis** [comment]
Unfortunately, I'm not using rafael.js. May be I'll start again with it...

**Comment by inorganik** [comment]
The dots problem shouldn't happen on any browser if you're using 1.5.1.

**Comment by kimwebParis** [comment]
Did you try my link ? I'm using 1.5.1...

**Comment by inorganik** [comment]
Won't load.... times out.

**Comment by kimwebParis** [comment]
really ? This is weird... Can I send you my file ?

**Comment by inorganik** [comment]
I don't have time for that. But if you want, you can look at my (open-source) tester page, and look for differences between your files and mine. Mine doesn't have the dots problem - http://inorganik.github.io/lazy-line-painter/

**Comment by kimwebParis** [comment]
It seems that you have too but very much less than me. Thank for your help anyway. I think I'll try with an old version with rafael.js

**Comment by inorganik** [comment]
I can tell you from experience that you'll definitely get dots with the old version with rapheal

**Comment by kimwebParis** [comment]
I just made a test with 1.1 and that solve my problem, like camilawaz said. Too bad because I usually prefer use latests versions...

**Comment by inorganik** [comment]
If you try it on Mobile Safari you'll get dots...

**Comment by kimwebParis** [comment]
Hi,
after some researches, I changed one line in jquery.lazylinepainter-1.5.1.js and the dots issue is less important now.
I just replaced line 130
var length = path.getTotalLength();
by
var length = Math.round(path.getTotalLength()*100)/100;

**Comment by romain-granai** [comment]
Hi,
I had the same issue, and I solved it like this : 
- using the older version of jquery.lazylinepainter - 1.1 I guess
- using raphael.js

Actually I tried the threehouse demo : http://treehouse-blog.s3.amazonaws.com/SVG%20Animations/initializr/index.html
which is working fine on all browsers, than you can do exactly the same as them.
it's working in Firefox, Chrome, safari and .... IE8. without any dots...

**Comment by saccodd** [comment]
Hi all! I have the same issue and I tried all solutions above. The older version + raphael do not draw those dots at all during the line painting. Any news?

**Comment by kimwebParis** [comment]
Hello!
I ended up working with another script, not very easy to scenarize but almost perfect for me.
https://maxwellito.github.io/vivus/

**Comment by tiina1** [comment]
I had the same problem in Mozilla with 1.5.1, it looked like that every point where a new line started had a dot. Defining strokeCap to butt fixed it for me.

**Comment by camoconnell** [comment]
c3bdeab
