### ISSUE TITLE
Multiple animation in the same page

### ISSUE THREAD

**Issue by tommibv** [camoconnell/lazy-line-painter#38]
Hi! Nice plugin thank you but I have an issue because I have trigged animation after clicking buttons!!

In other words I have a page like:

<div>                                                       
          <button></button>                       
           <div></div>                                  
</div>

<div>                                                    
         <button></button>                       
          <div></div>                                
</div>

Each button starts the animation of the next page, but I don't know why after added the second svg the first don't appear

**Comment by camoconnell** [comment]
This issue was related to a bug with the 'overrideKey', which caused it to overwrite path info. 
I;m happy to say this has been corrected in commit 2c6ae28
