### ISSUE TITLE
adding color inside svg

### ISSUE THREAD

**Issue by clestcruz** [camoconnell/lazy-line-painter#39]
Is there a way were I can add color inside the SVG. I was looking at the documentation hoping to finding something like "fill" to put color inside the SVG. Basically the concept is once the svg finishes animating it will add color inside.

**Comment by Feast-DG** [comment]
+1

**Comment by rmak78** [comment]
+1

**Comment by jammer99** [comment]
+1

**Comment by camoconnell** [comment]
Will look at integrating this feature into the next release!

**Comment by rmak78** [comment]
Thank you.. much appreciated.

**Comment by Nikkolas** [comment]
+1

**Comment by DanaJDavis** [comment]
I think a simple way to add fill color would be to create the filled image as a .png, run the plugin, remove, then .show() the .jpg upon the removal of the .svg. Checkout denisechandler.com . She uses the plugin on her front page with some tentacles. I inspected it using dev tools and saw that she uses the process i described above.

**Comment by camoconnell** [comment]
example of animating fill inside shape using path events;
https://codepen.io/camoconnell/pen/vvKWzP
