### ISSUE TITLE
svgData[target] Error

### ISSUE THREAD

**Issue by vongit** [camoconnell/lazy-line-painter#40]
I am getting the following error and no painting happens:

TypeError: options.svgData[target] is undefined
var w = options.svgData[target].dimensions.width;

The width seems to be set both in the js and css and I have not changed anything in the lazylinepainter.js file.

If anyone is available to help me troubleshoot this I would greatly appreciate it.

I am using v1.5.1

**Comment by camoconnell** [comment]
For future reference,
This issue has been explained in ticket #34.
Cheers
