### ISSUE TITLE
Use with skrollr

### ISSUE THREAD

**Issue by iris27** [camoconnell/lazy-line-painter#43]
Hi! I really enjoyed using this plugin. Is it possible to use this with Skrollr.js? If yes, how do I do this?Thanks!

**Comment by camoconnell** [comment]
Hi there, i added a "set" function which expects a ratio from 0 - 1.
You should be able to derive a ratio from Skrollr and call the set function on LLP.
See example;
https://github.com/camoconnell/lazy-line-painter/tree/master/examples/set
