### ISSUE TITLE
JS error in Safari (v1.6.2) preventing the ('erase') / ('paint') API functionality

### ISSUE THREAD

**Issue by SkyPages** [camoconnell/lazy-line-painter#51]
Console says it is on line 16
```
var c = k(this), a = c.data("lazyLinePainter");
```

Just thought you ought to be aware of it. Works fine in Chrome though.

**Comment by camoconnell** [comment]
Hey SkyPages,

I've just checked erase / paint on Safari, using the api example and it's working.
/examples/api.html

Could you please check again,
i may have addressed this issue in between 1.6.2 and the current build.

cheers
