### ISSUE TITLE
No stroke-dasharray available via CSS

### ISSUE THREAD

**Issue by Eggotron** [camoconnell/lazy-line-painter#54]
Hello people.

First of all excuse my English. Hope you can understand the point.

From the code in the jquery.lazylinepainter.js file I can gather (from my lack of better knowledge of JavaScript and jQuery) that the dasharray allows the script to animate the line. How can I alter this property so I can have, lets say, a dashed line or a dotted one?

Thanks.

--Update--

I tried adding the property in the var of the pathObj (Were all the info from the SVG goes) but it doesnt work, also tried in CSS with div > svg > path { stroke-dasharray: 5,5 } and it makes it dashed but not animated.

**Comment by camoconnell** [comment]
Hey Eggotron,

Great question, i'll look at adding this over the coming days.

**Comment by camoconnell** [comment]
Hey Eggotron,

I'm happy to announce the strokeDash attribute is back, with the release of 1.7.0!
You can set "strokeDash" on individual paths in your svgData obj or on the entire animation.

**Comment by Eggotron** [comment]
Thank you very much camoconell. Updating the version in the site and works incredibly.
