### ISSUE TITLE
Dot's Before Drawing on IE

### ISSUE THREAD

**Issue by EukleiaCraig** [camoconnell/lazy-line-painter#57]
Hi this is an issue that seems to effect version 1.5 - 1.7 on Internet Explorer 11 and 10. 

Before the lines are drawn on the start points appear as little circles like so:-

![lazy-problem](https://cloud.githubusercontent.com/assets/14541773/10543268/5b648720-7415-11e5-850d-7f540b292002.png)

I'm happy to provide more information if it helps.

**Comment by rmobis** [comment]
The same is happening on my Chrome since the last few updates. My current version is 47.0.2526.73 m.

**Comment by IndigoStarfish** [comment]
Same Issue on:
- Chrome 47.0.2526.73 m
- IE 10.0.9200.17556
- Firefox 37.0.2

Works fine on:
- Chrome 46.0.2490.86 m
- Opera 33.0.1990.115

(All Windows 8 or 10, jquery.lazylinepainter-1.7.0.min.js)

We upgraded the one on Chrome 46.0.2490.86 m to Chrome 47.0.2526.73 m; which made it show the dots.

**Comment by IndigoStarfish** [comment]
Currently ~~working~~ hacking around this by setting the opacity to 0, and then back to 1 when the stroke starts.

```javascript
$canvas.lazylinepainter({
	// ...
	'strokeOpacity': 0,
	'onStrokeStart': function(data) {
		data.el.style.strokeOpacity = 1;
	}
});
```

Note this won't work for animations you play repeatedly/loop, you'll have to find some way of resetting the opacity.
