### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dimensions' of undefined

### ISSUE THREAD

**Issue by agilBAKA** [camoconnell/lazy-line-painter#58]
var svgData = {
            "mobilephone29": {
                "strokepath": [
                    {
                        "path": "M647 2539 c-60 -46 -57 31 -57 -1259 0 -1294 -4 -1215 59 -1259 29 -21 38 -21 631 -21 593 0 602 0 631 21 63 44 59 -35 59 1259 0 1294 4 1215 -59 1259 -29 21 -37 21 -633 21 -594 -1 -603 -1 -631 -21z m1221 -171 l3 -88 -591 0 -590 0 0 83 c0 46 3 87 7 90 3 4 268 6 587 5 l581 -3 3 -87z m2 -1073 l0 -875 -590 0 -590 0 0 875 0 875 590 0 590 0 0 -875z m-2 -1082 l-3 -108 -585 0 -585 0 -3 108 -3 107 591 0 591 0 -3 -107z",
                        "duration": 800
                    },
                    {
                        "path": "M1244 278 c-24 -11 -44 -48 -44 -79 0 -31 44 -69 80 -69 36 0 80 38 80 69 0 33 -21 68 -47 80 -29 13 -41 13 -69 -1z",
                        "duration": 600
                    }
                ],
                "dimensions": {
                    "width": 256,
                    "height": 256
                }
            }
        };

```
    $(document).ready(function(){ 
        $('#logo').lazylinepainter( 
            {
                "svgData": svgData,
                "strokeWidth": 2,
                "strokeColor": "#e09b99"
            });

        $('#logo').lazylinepainter('paint'); 
     });
```

What is wrong with my code?

**Comment by Ayolland** [comment]
Counter-intuitively, Lazylinepainter appears to require that your SVG be named the exact same thing as the element it will be painted in. In this case, if you change "mobilephone29" to "logo" or vice versa, this should work.

**Comment by camoconnell** [comment]
svgData has been removed as a requirement in version In 1.9.0. 
Circumventing such naming issues
