### ISSUE TITLE
Dots appearing before paths animate

### ISSUE THREAD

**Issue by acollins1991** [camoconnell/lazy-line-painter#65]
Hi,

Is there a way to stop dots appearing before the path animates (see attached)??

![lazy line painter dots](https://cloud.githubusercontent.com/assets/13836056/15501915/7226b9ba-21a8-11e6-993c-6558b9980f1d.jpg)

Thanks

(Also, thanks for a great library!)

**Comment by camoconnell** [comment]
Resolved in 1.9.1 for dashStroke lines
