### ISSUE TITLE
Is it possible to fill the SVG graphic after the lines are painted

### ISSUE THREAD

**Issue by studioleland** [camoconnell/lazy-line-painter#66]
Very interested.

**Comment by JamesJGoodwin** [comment]
I'm using this piece of code:

`'onStrokeComplete':  function(){$('#goodwin-logo svg path').attr({'fill': '#fff', 'fill-opacity': '1'});}`

**Comment by DanaJDavis** [comment]
Check out my answer on this issue. It describes a simple way to fill the svg.
https://github.com/camoconnell/lazy-line-painter/issues/39

**Comment by camoconnell** [comment]
For future reference.

This is now ease to achieve using the rewritten events.
You can subscribe to Individual path events like so;
```
myAnimation.on('start:id-0', (event) => { // hide fill });
myAnimation.on('complete:id-0', (event) => { // show fill });
```
example;
https://codepen.io/camoconnell/pen/vvKWzP
