### ISSUE TITLE
[BUG] "I" are removed from original SVG

### ISSUE THREAD

**Issue by Robouste** [camoconnell/lazy-line-painter#69]
Hi, 

I have a strange problem, in my svg, all the "I" are removed but the path are present in the generated css.
Here is the svg :
[inspire.zip](https://github.com/camoconnell/lazy-line-painter/files/864381/inspire.zip)

And the result :
![result](https://cloud.githubusercontent.com/assets/5463032/24243665/2c215eae-0fbc-11e7-99d4-e558e026a20c.PNG)

What am I doing wrong ?

Thanks

**Comment by camoconnell** [comment]
Fixed in 1.9.0 - now supports all basic shapes
