### ISSUE TITLE
How to use in Visual Composer?

### ISSUE THREAD

**Issue by ponyboy0407** [camoconnell/lazy-line-painter#70]
Hi,
Your platform worked beautifully to create my animation, but when I copy and paste the code over to my site, nothing appears. I use Visual Composer & select the Raw JS add on. Then I place your code inside the quotes (img 1 and img 2.) When I load the page, though, nothing appears.

I'm still new to this and very self-taught. Do I need to enter html somewhere as well? Do I need to add anything to the code? If you are able to help me, I will be happy to make a donation to your main page.
![img1](https://cloud.githubusercontent.com/assets/28020031/25402946/7f6da056-29c8-11e7-9238-2033dc04ae23.PNG)
![img2](https://cloud.githubusercontent.com/assets/28020031/25402947/7f6df236-29c8-11e7-9738-70e0fdf57ec8.PNG)
![img3](https://cloud.githubusercontent.com/assets/28020031/25402948/7f6f2886-29c8-11e7-805b-1b27c5b7b4a0.PNG)

**Comment by camoconnell** [comment]
Apologies - later answer.
The code should be within the script tags rather than within the alert() function, as you had it.
