### ISSUE TITLE
Would you please update npm?

### ISSUE THREAD

**Issue by okutani-t** [camoconnell/lazy-line-painter#72]
Hi,

I want to get latest lazy-line-painter(1.8.0) using npm.

'Removed : jQuery as dependency' , very good!

https://www.npmjs.com/package/lazy-line-painter

Would you please update npm?

**Comment by camoconnell** [comment]
Hey okutani-t!
Thanks for getting in contact.

I'm planning a release on Monday the 17th of Dec for 1.9.0.
1.9.0 will be deployed to npm, it includes a number of substantial improvements.
- Removed need for svgData obj, animation properties for each path now stored on SVG.
- Refactored Event Handling
- Added support for additional shapes
  - polygons, circles, ellipses, polylines, lines, rects!

**Comment by okutani-t** [comment]
Hi camoconnell

That's great!  I am looking forward to the release of the latest version 1.9.0.

Thanks :)

**Comment by camoconnell** [comment]
1.9.0 has been published to NPM
