### ISSUE TITLE
Demo website is down

### ISSUE THREAD

**Issue by astridhanghoej** [camoconnell/lazy-line-painter#85]
https://lazylinepainter.info/ is no longer demo-ing the lazy line painter repo.

It is currently showing a website advertisting VPN services.

**Comment by guilhermesimoes** [comment]
Sad

**Comment by camoconnell** [comment]
Hey Guilherme,

Thanks for the feedback.
I had an issue with my hosting service, will try to get it back up and running soon.

Cheers Cam
