### ISSUE TITLE
Website link incorrect

### ISSUE THREAD

**Issue by Rice-Tech** [camoconnell/lazy-line-painter#86]
The link to a web demo for this project [https://lazylinepainter.info/](https://lazylinepainter.info/) seems to be a website trying to sell VPNs.

**Comment by merri-ment** [comment]
That url got hijacked, I have informed Google to de-index it. I managed to secure lazylinepainter.com. README has been updated, thanks.

**Comment by Rice-Tech** [comment]
Please also change it in the project description: 
![IMG_2290](https://github.com/merri-ment/lazy-line-painter/assets/101439807/9229e36e-9ece-460e-9a49-9f1efb190a2a)

**Comment by merri-ment** [comment]
Thanks @Rice-Tech, will update!

**Comment by merri-ment** [comment]
Updated
